php-version = "8.4.0"

[source]
workspace = "."
paths = ["src/", "test/"]
includes = ["vendor"]
excludes = []

[formatter]
print-width = 140
tab-width = 4
use-tabs = false
null-type-hint = "question"
space-after-logical-not-unary-prefix-operator = false
space-before-arrow-function-parameter-list-parenthesis = false
always-break-named-arguments-list = false
preserve-breaking-member-access-chain = true
preserve-breaking-argument-list = true
preserve-breaking-array-like = true
preserve-breaking-parameter-list = true
preserve-breaking-attribute-list = true
preserve-breaking-conditional-expression = true
empty-line-after-opening-tag = false

[linter]
excludes = ["tests/"]
integrations = ["symfony", "phpunit"]

[linter.rules]
literal-named-argument = { enabled = false }
no-boolean-flag-parameter = { enabled = false }
no-protected-in-final = { enabled = false }
too-many-properties = { threshold = 50 }
too-many-enum-cases = { threshold = 80 }
excessive-nesting = { threshold = 10 }
no-multi-assignments = { enabled = false }
no-empty = { enabled = false }
no-error-control-operator = { enabled = false }
too-many-methods = { enabled = false }
no-ini-set = { enabled = false }
excessive-parameter-list = { enabled = false }
cyclomatic-complexity = { enabled = false }
halstead = { enabled = false }
kan-defect = { enabled = false }
# no-shorthand-ternary = { enabled = false }
no-else-clause = { enabled = false }
no-assign-in-condition = { enabled = false }
no-empty-catch-clause = { enabled = false }
no-redundant-use = { enabled = false }
