php-version = "8.4.0"

[source]
workspace = "."
paths = ["src", "tests"]
includes = ["vendor"]
excludes = []

[formatter]
print-width = 120
tab-width = 4
use-tabs = false

[linter]
integrations = ["symfony", "phpunit"]

[linter.rules]
ambiguous-function-call = { enabled = false }
literal-named-argument = { enabled = false }
halstead = { enabled = false }
assertion-style = { enabled = false }
no-empty = { enabled = false }
kan-defect = { enabled = false }
cyclomatic-complexity = { enabled = false }
prefer-static-closure = { enabled = false }
too-many-methods = { enabled = false }
no-error-control-operator = { enabled = false }
no-boolean-flag-parameter = { enabled = false }
no-else-clause = { enabled = false }
assert-description = { enabled = false }
no-ini-set = { enabled = false }
no-multi-assignments = { enabled = false }
excessive-parameter-list = { enabled = false }
function-name = { camel = true, either = true }
no-literal-password = { enabled = false }
class-name = { enabled = false }

[analyzer]
find-unused-definitions = true
find-unused-expressions = false
analyze-dead-code = false
memoize-properties = true
allow-possibly-undefined-array-keys = true
check-throws = false
perform-heuristic-checks = true
strict-list-index-checks = false
no-boolean-literal-comparison = false
check-missing-type-hints = false
register-super-globals = true
